"""add mystery number

Revision ID: 7754d12fb265
Revises: e2e091996f1f
Create Date: 2025-11-26 10:58:28.429055

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7754d12fb265"
down_revision = "e2e091996f1f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mystery_number", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entry", schema=None) as batch_op:
        batch_op.drop_column("mystery_number")

    # ### end Alembic commands ###
